#!/usr/bin/Rscript

source('script.R')

constants <- c(
"letters", 
"LETTERS", 
"pi", 
"month.abb", 
"month.name", "pi", 
"state.abb", 
"state.area",
"state.center",
"state.division",
"state.name",
"state.region",
"state.x77" 
)


for(constant in constants){
    tryCatch(
        {learn(constant)},
        error=function(e){
            msg <- as.character(e)
            return(msg)
        }
    )
}
